name: flutter_base
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.8.1
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.0
  equatable: ^2.0.7
  flutter_markdown: ^0.7.4+3
  flutter_native_splash: ^2.3.1
  rive: ^0.13.20
  google_maps_flutter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.3.0
  json_serializable: ^6.7.1
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/about/
    - assets/splash/
    - assets/rive/
  
flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/app/utils/gen/localized
  arb_dir: assets/localizations
  class_name: AppLocalized
