name: flutter_base
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: 2.8.4
  intl: 0.18.0
  cupertino_icons: 1.0.5
  get_it: 7.6.0
  injectable: 2.2.0
  json_annotation: ^4.8.1
  auto_route: 7.8.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.0
  equatable: 2.0.5
  flutter_markdown: ^0.6.17+1
  flutter_native_splash: ^2.3.1
  rive: ^0.11.14
  google_maps_flutter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: 2.4.6
  injectable_generator: ^2.3.0
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.1
  freezed: 2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/about/
    - assets/splash/
    - assets/rive/
  
flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/app/utils/gen/localized
  arb_dir: assets/localizations
  class_name: AppLocalized
